// Server routes for the web feature group "coach" (SPEC 6 AC-94, 6.3 AC-156 / AC-162 / AC-168).
//   - OCR files for the phone (D-11: worker, core and English data come from the hub, never a CDN)
//   - approved screenshot parse rules (P-16, 4.18)
//   - the Coach day timeline (class schedule + cards due)
//   - the portfolio builder (B-7) and the team-level wall (G-2, G-3)
// Coach data itself (plan versions, tracker entries) never reaches this module: it lives encrypted in the
// learner's personal database and travels through /db/* (the sync guard refuses plaintext and minors).
import { existsSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { isOn, switchDefaults } from '../../../../core/src/index.ts';

const esc = (s: unknown): string => String(s ?? '').replace(/[&<>"']/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch] as string));

// Only these names are served; no path from the request ever reaches the file system.
const OCR_CORE = new Set([
  'tesseract-core.wasm.js', 'tesseract-core-lstm.wasm.js', 'tesseract-core-simd.wasm.js', 'tesseract-core-simd-lstm.wasm.js',
  'tesseract-core-relaxedsimd.wasm.js', 'tesseract-core-relaxedsimd-lstm.wasm.js',
]);

function packageDir(name: string, root: string): string | null {
  try {
    const req = createRequire(join(root, 'package.json'));
    return dirname(req.resolve(`${name}/package.json`));
  } catch { return null; }
}

// Where the English data may live on the hub: LMS_TESSDATA_DIR first, then the hub's own data folder.
export function tessdataPath(root: string, dataDir: string, env: Record<string, string | undefined> = process.env): string | null {
  const dirs = [env.LMS_TESSDATA_DIR, join(dataDir, 'tessdata'), join(root, 'packages', 'server', 'assets', 'tessdata')].filter(Boolean) as string[];
  for (const d of dirs) {
    const f = resolve(d, 'eng.traineddata.gz');
    if (existsSync(f)) return f;
  }
  return null;
}

export function portfolioHtml(input: {
  name: string; org: string; primary: string; text: string;
  repos: { label: string; url: string }[]; badges: { name: string; team: string }[]; certificates: { certId: string; programName: string }[];
}): string {
  const list = (items: string[], empty: string) => (items.length ? `<ul>${items.join('')}</ul>` : `<p>${esc(empty)}</p>`);
  const repos = list(input.repos.map((r) => `<li><a href="${esc(r.url)}" rel="noreferrer noopener" target="_blank">${esc(r.label)}</a></li>`), 'No repositories yet.');
  const badges = list(input.badges.map((b) => `<li>${esc(b.name)} (team ${esc(b.team)})</li>`), 'No badges yet.');
  const certs = list(input.certificates.map((c) => `<li>${esc(c.programName || 'Certificate')}: <a href="/verify/${esc(c.certId)}" target="_blank" rel="noreferrer noopener">${esc(c.certId)}</a></li>`), 'No certificates yet.');
  const primary = /^#[0-9a-fA-F]{6}$/.test(input.primary) ? input.primary : '#1d4ed8';
  const text = /^#[0-9a-fA-F]{6}$/.test(input.text) ? input.text : '#1a1a1a';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(input.name)} portfolio</title><style>body{font:16px/1.5 system-ui,sans-serif;margin:0;padding:16px;color:${text};background:#fff}main{max-width:640px;margin:0 auto}h1{color:#1a1a1a;border-bottom:4px solid ${primary};padding-bottom:8px}h2{font-size:1.25rem;margin-top:24px}a{color:#1d4ed8}footer{margin-top:32px;color:#4a4a4a;font-size:.875rem}</style></head><body><main><h1>${esc(input.name)}</h1><p>Portfolio built from the ${esc(input.org)} hub template.</p><h2>Repositories</h2>${repos}<h2>Badges</h2>${badges}<h2>Certificates</h2>${certs}<footer>Generated by ${esc(input.org)}.</footer></main></body></html>`;
}

export function register(app: any, ctx: any): void {
  const { store, ids } = ctx;
  const L = ctx.guard.role('learner');
  const stamp = (by: string) => ({ schema: ctx.schema, updatedAt: ctx.clock.now(), updatedBy: by });
  const who = (c: any): string => `person:${c.get('session').personId}`;
  const classKeys = (): string[] => store.names().filter((n: string) => n.startsWith('class-')).map((n: string) => n.slice(6));
  const root: string = ctx.config.repoRoot;

  // ---- OCR files from the hub (D-11) ----
  const asset = (file: string | null, type: string, c: any) => {
    if (!file || !existsSync(file)) return c.json({ error: { file: 'not-available' } }, 404);
    return c.body(readFileSync(file), 200, { 'content-type': type, 'cache-control': 'public, max-age=86400' });
  };
  app.get('/api/coach/ocr/worker.min.js', (c: any) => {
    const dir = packageDir('tesseract.js', root);
    return asset(dir ? join(dir, 'dist', 'worker.min.js') : null, 'text/javascript', c);
  });
  app.get('/api/coach/ocr/core/:file', (c: any) => {
    const name = String(c.req.param('file'));
    const dir = packageDir('tesseract.js-core', root);
    return asset(OCR_CORE.has(name) && dir ? join(dir, name) : null, 'text/javascript', c);
  });
  app.get('/api/coach/ocr/lang/eng.traineddata.gz', (c: any) => asset(tessdataPath(root, ctx.config.dataDir), 'application/gzip', c));
  app.get('/api/coach/ocr/status', (c: any) => c.json({ english: tessdataPath(root, ctx.config.dataDir) !== null }));

  // ---- approved screenshot rules (P-16): the phone never runs rules a person has not approved ----
  app.get('/api/coach/parse-rules', async (c: any) => {
    const rules = (await store.list('org', 'parseRules:')).filter((r: any) => typeof r.approvedBy === 'string' && r.approvedBy !== '');
    return c.json({ rules: rules.map((r: any) => ({ id: r.id, app: r.app, fields: r.fields })) });
  });

  // ---- the learner's class ----
  async function enrolled(db: string, key: string) {
    return (await store.list(db, 'enrolment:')).find((e: any) => ids.keyOf(String(e.personId ?? e.id)) === key && e.status !== 'dropped') ?? null;
  }
  async function myClass(c: any) {
    const me = ids.keyOf(c.get('session').personId);
    for (const key of classKeys()) {
      const doc = await store.get(`class-${key}`, `class:${key}`);
      if (doc && await enrolled(`class-${key}`, me)) return { key, db: `class-${key}`, doc, me };
    }
    return null;
  }
  async function switchesFor(cls: any): Promise<Record<string, boolean>> {
    const org = (await store.get('org', 'org:main')) ?? {};
    const cohort = cls?.cohortId ? await store.get('org', cls.cohortId) : null;
    const program = cohort?.programId ? await store.get('org', cohort.programId) : null;
    const layers = { class: cls?.switches ?? {}, program: program?.switches ?? {}, org: org.switches ?? {} };
    const out: Record<string, boolean> = {};
    for (const k of Object.keys(switchDefaults())) out[k] = isOn(k, layers);
    return out;
  }

  // ---- the Coach day timeline (AC-156): study blocks from the class schedule, cards due ----
  app.get('/api/coach/timeline', L, async (c: any) => {
    const mine = await myClass(c);
    const now = ctx.clock.now();
    const person = ids.keyOf(c.get('session').personId);
    const cards = (await store.list(`person-${person}`, 'card:')).filter((x: any) => Number(x.fsrs?.due ?? 0) <= now);
    if (!mine) return c.json({ classId: null, className: '', today: null, days: [], cardsDue: cards.length, now });
    const dayDocs = await store.list(mine.db, 'day:');
    const schedule: any[] = mine.doc.schedule ?? [];
    const todayIso = new Date(now + 5.5 * 3600_000).toISOString().slice(0, 10); // program time zone Asia/Kolkata (D-27)
    const days = schedule.map((s, index) => {
      const doc = dayDocs.find((d: any) => d.index === index);
      const released: string[] = doc?.released ?? [];
      return {
        index, date: s.date, start: s.start, end: s.end,
        sections: (doc?.sections ?? []).map((sec: any) => ({
          id: sec.id, title: sec.title, plannedSec: sec.plannedSec ?? 0, graded: !!sec.graded, kind: sec.kind ?? '', released: released.includes(sec.id),
        })),
      };
    });
    const todayIdx = days.findIndex((d) => d.date === todayIso);
    return c.json({ classId: mine.doc.id, className: mine.doc.name, today: todayIdx >= 0 ? todayIdx : null, days, cardsDue: cards.length, now });
  });

  // ---- portfolio (B-7): a small static site from the hub's template, kept in the learner's personal database ----
  async function buildSite(c: any) {
    const key = ids.keyOf(c.get('session').personId);
    const person = (await store.get('org', `person:${key}`)) ?? {};
    const org = (await store.get('org', 'org:main')) ?? {};
    const mine = await myClass(c);
    const repos: { label: string; url: string }[] = [];
    if (person.githubUser) repos.push({ label: `GitHub: ${person.githubUser}`, url: `https://github.com/${encodeURIComponent(person.githubUser)}` });
    if (person.forgeUser && process.env.LMS_FORGEJO_URL) repos.push({ label: `Practice forge: ${person.forgeUser}`, url: `${String(process.env.LMS_FORGEJO_URL).replace(/\/$/, '')}/${encodeURIComponent(person.forgeUser)}` });
    const badges: { name: string; team: string }[] = [];
    if (mine) {
      for (const tk of (await store.list(mine.db, 'ticket:')).filter((x: any) => ids.keyOf(String(x.assignee ?? '')) === key && x.forgeRef)) repos.push({ label: String(tk.forgeRef), url: String(tk.forgeRef) });
      const teams: Record<string, string[]> = mine.doc.teams ?? {};
      const myTeams = Object.keys(teams).filter((tm) => (teams[tm] ?? []).some((p) => ids.keyOf(p) === key));
      for (const b of await store.list(mine.db, 'badge:')) if (myTeams.includes(b.teamId)) badges.push({ name: b.name, team: b.teamId });
    }
    const certificates: { certId: string; programName: string }[] = [];
    for (const cert of (await store.list('org', 'certificate:')).filter((x: any) => ids.keyOf(String(x.personId)) === key)) {
      const program = await store.get('org', cert.programId);
      certificates.push({ certId: cert.certId, programName: program?.name ?? '' });
    }
    const html = portfolioHtml({
      name: person.name || key, org: org.name || 'Coach LMS', primary: org.brand?.colours?.primary ?? '', text: org.brand?.colours?.text ?? '',
      repos: repos.filter((r) => /^https?:\/\//.test(r.url)), badges, certificates,
    });
    return { html, counts: { repos: repos.length, badges: badges.length, certificates: certificates.length } };
  }
  app.post('/api/coach/portfolio', L, async (c: any) => {
    const key = ids.keyOf(c.get('session').personId);
    const { html, counts } = await buildSite(c);
    const prev = await store.get(`person-${key}`, 'portfolio:site');
    const version = (prev?.version ?? 0) + 1;
    await store.put(`person-${key}`, { type: 'portfolio', id: 'portfolio:site', version, html, counts, ...stamp(who(c)) });
    return c.json({ version, counts, url: '/api/coach/portfolio/site' });
  });
  app.get('/api/coach/portfolio', L, async (c: any) => {
    const doc = await store.get(`person-${ids.keyOf(c.get('session').personId)}`, 'portfolio:site');
    return c.json(doc ? { built: true, version: doc.version, counts: doc.counts, url: '/api/coach/portfolio/site' } : { built: false });
  });
  app.get('/api/coach/portfolio/site', L, async (c: any) => {
    const doc = await store.get(`person-${ids.keyOf(c.get('session').personId)}`, 'portfolio:site');
    if (!doc) return c.json({ error: { portfolio: 'not-built' } }, 404);
    return c.body(doc.html, 200, {
      'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store',
      'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'",
    });
  });

  // ---- team-level wall (G-2, G-3): badges and merged pull requests per team, never per person ----
  app.get('/api/coach/wall', L, async (c: any) => {
    const mine = await myClass(c);
    if (!mine) return c.json({ badgesOn: true, wallOn: true, teams: [] });
    const sw = await switchesFor(mine.doc);
    const teams: Record<string, string[]> = mine.doc.teams ?? {};
    const badges = sw.teamBadges ? await store.list(mine.db, 'badge:') : [];
    const merged = sw.celebrationWall
      ? (await store.list(mine.db, 'ticket:')).filter((x: any) => x.forgeRef && /^(merged|done)$/.test(String(x.status ?? '')))
      : [];
    const teamOf = (personRef: string) => Object.keys(teams).find((tm) => (teams[tm] ?? []).some((p) => ids.keyOf(p) === ids.keyOf(personRef)));
    const out = Object.keys(teams).sort().map((teamId) => ({
      teamId,
      badges: badges.filter((b: any) => b.teamId === teamId).map((b: any) => ({ name: b.name, at: b.at })),
      mergedPrs: merged.filter((x: any) => x.assignee && teamOf(String(x.assignee)) === teamId).length,
    }));
    return c.json({ badgesOn: sw.teamBadges, wallOn: sw.celebrationWall, teams: out });
  });

  // ---- switches that shape the learner's screens (Heading Strike G-1, story mode G-4) ----
  app.get('/api/coach/switches', async (c: any) => {
    const mine = await myClass(c);
    const sw = await switchesFor(mine?.doc ?? null);
    return c.json({ headingStrike: sw.headingStrike, storyMode: sw.storyMode, teamBadges: sw.teamBadges, celebrationWall: sw.celebrationWall });
  });
}
