// Post-processing: title card (HTML frame rendered by Chromium) + the recording -> H.264 mp4, and out/index.md.
import { spawnSync } from 'node:child_process';
import { writeFileSync, readdirSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const FFMPEG = process.env.FFMPEG || '/usr/bin/ffmpeg';
const FFPROBE = process.env.FFPROBE || '/usr/bin/ffprobe';
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');

export function probeSeconds(file) {
  const r = spawnSync(FFPROBE, ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', file], { encoding: 'utf8' });
  return Number.parseFloat(r.stdout) || 0;
}

/** Renders a 2-second-title frame as PNG using the already running browser. */
export async function titleFrame(browser, { title, subtitle, width, height, scale = 1, file }) {
  const ctx = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: scale });
  const page = await ctx.newPage();
  const big = Math.round(Math.min(width, height * 1.4) / (width < 600 ? 9 : 14));
  await page.setContent(`<!doctype html><meta charset="utf-8"><body style="margin:0;width:${width}px;height:${height}px;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#0b1220,#1d4ed8);font-family:system-ui,'Segoe UI',Roboto,sans-serif;color:#fff;text-align:center">
    <div style="padding:0 ${Math.round(width * 0.07)}px">
      <div style="font-size:${Math.round(big * 0.5)}px;letter-spacing:.2em;text-transform:uppercase;color:#ffc400;font-weight:700;margin-bottom:${Math.round(big * 0.5)}px">Coach LMS &middot; product demo</div>
      <div style="font-size:${big}px;font-weight:800;line-height:1.15">${esc(title)}</div>
      <div style="font-size:${Math.round(big * 0.45)}px;margin-top:${Math.round(big * 0.5)}px;opacity:.85">${esc(subtitle)}</div>
    </div></body>`);
  await page.screenshot({ path: file });
  await ctx.close();
}

/** title.png (2.5 s) + recording.webm -> out/<name>.mp4 (H.264, yuv420p, 25 fps, faststart). Returns the mp4 duration.
 *  The result is decoded once to prove it is intact; if not (seen once under memory pressure), it is encoded again with one thread. */
export function makeMp4({ webm, png, mp4, width, height }) {
  const vf = `scale=${width}:${height}:force_original_aspect_ratio=decrease,pad=${width}:${height}:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=25,format=yuv420p`;
  const encode = (threads) => {
    const args = ['-y', '-hide_banner', '-loglevel', 'error',
      '-loop', '1', '-framerate', '25', '-t', '2.5', '-i', png,
      '-i', webm,
      '-filter_complex', `[0:v]${vf}[a];[1:v]${vf}[b];[a][b]concat=n=2:v=1:a=0[v]`,
      '-map', '[v]', '-c:v', 'libx264', '-preset', 'medium', '-crf', '22', '-pix_fmt', 'yuv420p', '-threads', String(threads), '-movflags', '+faststart', mp4];
    const r = spawnSync(FFMPEG, args, { encoding: 'utf8' });
    if (r.status !== 0) throw new Error(`ffmpeg failed: ${r.stderr.slice(-800)}`);
    const v = spawnSync(FFMPEG, ['-v', 'error', '-i', mp4, '-f', 'null', '-'], { encoding: 'utf8' });
    return v.status === 0 && !v.stderr.trim();
  };
  if (!encode(0) && !encode(1)) throw new Error(`could not produce a clean ${mp4}`);
  return probeSeconds(mp4);
}

const mmss = (s) => `${Math.floor(s / 60)}:${String(Math.round(s % 60)).padStart(2, '0')}`;

/** Rebuilds out/index.md from every out/<name>.json written by the runner. */
export function writeIndex(outDir) {
  const metas = readdirSync(outDir).filter((f) => f.endsWith('.json')).sort().map((f) => JSON.parse(readFileSync(join(outDir, f), 'utf8')));
  const lines = ['# Coach LMS product demos', '', 'Generated by `node demos/run.mjs`. Each video starts with a 2-second title card; scene times are in the .mp4.', '',
    '| Video | Duration | Format | Scenes shown |', '|---|---|---|---|'];
  for (const m of metas) {
    const scenes = m.scenes.map((s) => `${mmss(s.at)} ${s.title}${s.failed ? ' (FAILED)' : ''}`).join('<br>');
    lines.push(`| \`${m.name}\` ${m.title} | ${mmss(m.seconds)} (${m.seconds.toFixed(1)} s) | ${m.size} ${m.profile} | ${scenes} |`);
  }
  lines.push('');
  for (const m of metas) {
    if (m.skipped?.length) {
      lines.push(`## Skipped in ${m.name}`, '');
      for (const s of m.skipped) lines.push(`- **${s.title}**: skipped, ${s.reason}`);
      lines.push('');
    }
    if (m.failures?.length) {
      lines.push(`## Failed in ${m.name}`, '');
      for (const f of m.failures) lines.push(`- ${f}`);
      lines.push('');
    }
  }
  writeFileSync(join(outDir, 'index.md'), lines.join('\n'));
}
