// Post-processing: title card (HTML frame rendered by Chromium) + the recording -> H.264 mp4, and out/index.md.
import { spawnSync } from 'node:child_process';
import { writeFileSync, readdirSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { coverageRows } from './coverage.mjs';

const FFMPEG = process.env.FFMPEG || '/usr/bin/ffmpeg';
const FFPROBE = process.env.FFPROBE || '/usr/bin/ffprobe';
export const TITLE_SECONDS = 2;
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');

export function probeSeconds(file) {
  const r = spawnSync(FFPROBE, ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', file], { encoding: 'utf8' });
  return Number.parseFloat(r.stdout) || 0;
}

/** Renders a 2-second-title frame as PNG using the already running browser. */
export async function titleFrame(browser, { title, subtitle, width, height, scale = 1, file }) {
  const ctx = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: scale });
  const page = await ctx.newPage();
  const big = Math.round(Math.min(width, height * 1.4) / (width < 600 ? 9 : 14));
  await page.setContent(`<!doctype html><meta charset="utf-8"><body style="margin:0;width:${width}px;height:${height}px;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#0b1220,#1d4ed8);font-family:system-ui,'Segoe UI',Roboto,sans-serif;color:#fff;text-align:center">
    <div style="padding:0 ${Math.round(width * 0.07)}px">
      <div style="font-size:${Math.round(big * 0.5)}px;letter-spacing:.2em;text-transform:uppercase;color:#ffc400;font-weight:700;margin-bottom:${Math.round(big * 0.5)}px">Coach LMS &middot; product demo</div>
      <div style="font-size:${big}px;font-weight:800;line-height:1.15">${esc(title)}</div>
      <div style="font-size:${Math.round(big * 0.45)}px;margin-top:${Math.round(big * 0.5)}px;opacity:.85">${esc(subtitle)}</div>
    </div></body>`);
  await page.screenshot({ path: file });
  await ctx.close();
}

/** title.png (2.5 s) + recording.webm -> out/<name>.mp4 (H.264, yuv420p, 25 fps, faststart). Returns the mp4 duration.
 *  The result is decoded once to prove it is intact; if not (seen once under memory pressure), it is encoded again with one thread. */
export function makeMp4({ webm, png, mp4, trim = 0, width, height }) {
  const vf = `scale=${width}:${height}:force_original_aspect_ratio=decrease,pad=${width}:${height}:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=25,format=yuv420p`;
  const encode = (threads) => {
    const args = ['-y', '-hide_banner', '-loglevel', 'error',
      '-loop', '1', '-framerate', '25', '-t', String(TITLE_SECONDS), '-i', png,
      '-ss', trim.toFixed(2), '-i', webm,
      '-filter_complex', `[0:v]${vf}[a];[1:v]${vf}[b];[a][b]concat=n=2:v=1:a=0[v]`,
      '-map', '[v]', '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '23', '-pix_fmt', 'yuv420p', '-threads', String(threads), '-movflags', '+faststart', mp4];
    const r = spawnSync(FFMPEG, args, { encoding: 'utf8' });
    if (r.status !== 0) throw new Error(`ffmpeg failed: ${r.stderr.slice(-800)}`);
    const v = spawnSync(FFMPEG, ['-v', 'error', '-i', mp4, '-f', 'null', '-'], { encoding: 'utf8' });
    return v.status === 0 && !v.stderr.trim();
  };
  if (!encode(0) && !encode(1)) throw new Error(`could not produce a clean ${mp4}`);
  return probeSeconds(mp4);
}

const mmss = (s) => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`;

/** Rebuilds out/index.md from every out/<name>.json written by the runner: the video table and the coverage table. */
export function writeIndex(outDir) {
  const metas = readdirSync(outDir).filter((f) => /^\d\d-.*\.json$/.test(f)).sort().map((f) => JSON.parse(readFileSync(join(outDir, f), 'utf8')));
  const cov = coverageRows(metas);
  const total = metas.reduce((a, m) => a + m.seconds, 0);
  const lines = ['# Coach LMS product demos', '',
    `Generated by \`node demos/run.mjs\`. ${metas.length} videos, ${mmss(total)} in all. Each starts with a ${TITLE_SECONDS}-second title card; times below are positions in the .mp4 (title card included).`,
    'Everything on screen is the real app running against a throw-away hub with invented people (Lena, Liam, Aarav and so on) and invented codes; nothing is mocked-up.', '',
    '## Videos', '', '| File | Persona | Device | Duration | What it shows |', '|---|---|---|---|---|'];
  for (const m of metas) {
    const dev = m.profile === 'phone' ? `phone, ${m.size}` : `desktop, ${m.size}`;
    lines.push(`| \`${m.name}.mp4\` | ${m.persona} | ${dev} | ${mmss(m.seconds)} (${m.seconds.toFixed(0)} s) | ${m.shows} |`);
  }
  lines.push('', '### Scene times', '');
  for (const m of metas) lines.push(`- **${m.name}**: ${m.scenes.map((s) => `${mmss(s.at)} ${s.title}${s.failed ? ' (FAILED)' : ''}`).join('; ')}`);
  lines.push('', '## Coverage: SPEC feature by video', '',
    `${cov.total} rows from SPEC section 4 (4.2 to 4.33), section 5, section 6 (including 6.3) and section 7. **${cov.shown} shown on screen, ${cov.notShown} not shown** (reason in the row).`, '',
    '| SPEC | Feature | Shown in (video@time) / not shown because |', '|---|---|---|');
  for (const r of cov.rows) lines.push(`| ${r.ref} | ${r.feature} | ${r.text} |`);
  const ns = cov.rows.filter((r) => !r.shown);
  lines.push('', '### Not shown, grouped by reason', '');
  const groups = new Map();
  for (const r of ns) { const k = r.text.replace(/^not shown: /, ''); (groups.get(k) ?? groups.set(k, []).get(k)).push(`${r.ref} ${r.feature}`); }
  for (const [reason, items] of groups) lines.push(`- ${reason}`, ...items.map((i) => `  - ${i}`));
  if (cov.unverified.length) lines.push('', '### Unverified rows (the scene was not found in the recordings on disk)', '', ...cov.unverified.map((u) => `- ${u}`));
  const skipped = metas.filter((m) => m.skipped?.length);
  if (skipped.length) {
    lines.push('', '## Scenes skipped because the app has no UI for them', '');
    for (const m of skipped) for (const s of m.skipped) lines.push(`- **${m.name}, ${s.title}**: ${s.reason}`);
  }
  const failed = metas.filter((m) => m.failures?.length);
  if (failed.length) {
    lines.push('', '## Failures during recording', '');
    for (const m of failed) for (const f of m.failures) lines.push(`- ${m.name}: ${f}`);
  }
  writeFileSync(join(outDir, 'index.md'), lines.join('\n') + '\n');
  return cov;
}
